apiVersion: v1
kind: Service
metadata:
  name: webhook-stage-service # ğŸ› ï¸
  namespace: instanode #ğŸš€
spec:
  selector:
    app: webhook-stage # Your deployment name ğŸ’¼
  ports:
    - protocol: TCP
      port: 80 #ğŸŒ
      targetPort: 4242 #ğŸ–¥ï¸
  type: ClusterIP #ğŸŒŸ
