apiVersion: v1
kind: Service
metadata:
  name: admin-stage-service # ğŸ› ï¸
  namespace: instanode #ğŸš€
spec:
  selector:
    app: admin-stage # Your deployment name ğŸ’¼
  ports:
    - protocol: TCP
      port: 80 #ğŸŒ
      targetPort: 3006 #ğŸ–¥ï¸
  type: ClusterIP #ğŸŒŸ
