apiVersion: v1
kind: Service
metadata:
  name: raas-stage-service # ğŸ› ï¸
  namespace: instanode #ğŸš€
spec:
  selector:
    app: raas-stage # Your deployment name ğŸ’¼
  ports:
    - protocol: TCP
      port: 80 #ğŸŒ
      targetPort: 3007 #ğŸ–¥ï¸
  type: ClusterIP #ğŸŒŸ
